name: pull_request

on:
  workflow_dispatch:
jobs:
  pull_request:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
      with:
        repository: tonasodji/test_pull_request
        
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        push-to-fork: tonasodji/test_pull_request_fork


  
  
