name: pull_request

on:
  workflow_dispatch:
jobs:
  pull_request:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3

    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1
      
    - name: file
      run: echo "ciao" > ciao
        
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}



  
  
